#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

# global settings
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:45:0 \
  layout bsp \
  mouse_follows_focus off \
  focus_follows_mouse autoraise \
  window_zoom_persist off \
  window_placement second_child \
  window_shadow off \
  window_opacity on \
  window_opacity_duration 0.2 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.9 \
  window_animation_duration 0.5 \
  window_animation_easing ease_out_quint \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  top_padding 8 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 10

# Exclude problematic apps from being managed:
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

# Ghostty
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

yabai -m signal --add apps='^Finder$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add apps='^Finder$' event=window_destroyed action='yabai -m space --layout bsp'

echo "yabai configuration loaded.."
